import { ColorSchemeScript } from "@mantine/core";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
// styles
import Footer from "@/components/footer";
import NavBar from "@/components/navbar";
import "@mantine/core/styles.css";
import clsx from "clsx";
import { Provider } from "./_providers";
import "./globals.scss";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Cargo Sender",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <ColorSchemeScript />
      </head>
      <body className={clsx(inter.className, "bg-backdrop")}>
        <Provider>
          <header>
            <NavBar />
          </header>
          {children}
          <Footer />
        </Provider>
      </body>
    </html>
  );
}
